import Provider from "./Provider"
import Main from "./Main"
import Footer from "./Footer"
import Header from "./Header"

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
  thmeColor: "#ffffff",
}

export default function RootLayout({ children }: { children: React.ReactNode }) {
  return (
    <html lang="ja">
      <head></head>
      <body>
        <Provider>
          <Header />
          <Main>{children}</Main>
          <Footer />
        </Provider>
      </body>
    </html>
  )
}
